variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test

lint:
  image: node:10.15.3
  stage: lint
  tags:
    - docker
  script:
    - npm install
    - npm run lint

test:
  image: node:10.15.3
  stage: test
  tags:
    - docker
  script:
    - npm install
    - npm test
